name: Automation CI

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  browserstack:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      APPIUM_URL: https://${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}@hub.browserstack.com/wd/hub
      APK_PATH: bs://2689d6631ff8888a06599ca0d46b12eed3a7a49f
      DEVICE_NAME: Samsung Galaxy S22 Ultra
      PLATFORM_NAME: Android
      PLATFORM_VERSION: "12.0"
      AUTOMATION_NAME: UiAutomator2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-${{ runner.os }}-
      - name: Tests
        run: mvn -B -q -Dtest=apptests.CucumberRunnerTest test
      - uses: actions/upload-artifact@v4
        with:
          name: bs-reports
          path: |
            reports/**
            target/surefire-reports/**
            target/cucumber-report.json

