name: Automation CI

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  browserstack:
    runs-on: [self-hosted, android, local]
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      APPIUM_URL: https://${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}@hub.browserstack.com/wd/hub
      APP_URL: bs://2689d6631ff8888a06599ca0d46b12eed3a7a49f
      DEVICE_NAME: Samsung Galaxy S22 Ultra
      PLATFORM_NAME: Android
      PLATFORM_VERSION: "12.0"
      AUTOMATION_NAME: UiAutomator2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run BrowserStack tests
        run: mvn -B -e -X -Dtest=apptests.CucumberRunnerTest test
      - uses: actions/upload-artifact@v4
        with:
          name: bs-reports
          path: |
            reports/**
            target/surefire-reports/**
            target/cucumber-report.json

  local_self_hosted:
    runs-on: [self-hosted, android, local]
    env:
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      APPIUM_URL: http://127.0.0.1:4723/wd/hub
      APP_URL: /home/saraperez/Downloads/app.apk
      AUTOMATION_NAME: UiAutomator2
      PLATFORM_NAME: Android
      PLATFORM_VERSION: "14"
      DEVICE_NAME: test
      AVD_NAME: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: npm install -g appium@next
      - run: nohup npx appium --base-path /wd/hub > appium.log 2>&1 &
      - name: Run Local tests
        run: mvn -B -e -X -Dtest=apptests.CucumberRunnerTest test
      - uses: actions/upload-artifact@v4
        with:
          name: local-reports
          path: |
            reports/**
            target/surefire-reports/**
            target/cucumber-report.json
