name: Automation CI

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  browserstack:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      APPIUM_URL: https://${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}@hub.browserstack.com/wd/hub
      APP_URL: bs://2689d6631ff8888a06599ca0d46b12eed3a7a49f
      DEVICE_NAME: Samsung Galaxy S22 Ultra
      PLATFORM_NAME: Android
      PLATFORM_VERSION: "12.0"
      AUTOMATION_NAME: UiAutomator2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-${{ runner.os }}-
      - name: Run Tests (debug)
        run: |
          mvn -B -e -X -Dtest=apptests.CucumberRunnerTest test \
            -DAPP_URL=${{ env.APP_URL }} \
            -DAPPIUM_URL=${{ env.APPIUM_URL }} \
            -DDEVICE_NAME="${{ env.DEVICE_NAME }}" \
            -DPLATFORM_VERSION="${{ env.PLATFORM_VERSION }}" \
            -DAUTOMATION_NAME=${{ env.AUTOMATION_NAME }} \
            -DLOGIN_EMAIL=${{ env.LOGIN_EMAIL }} \
            -DLOGIN_PASSWORD=${{ env.LOGIN_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bs-surefire-reports
          path: target/surefire-reports/**

  local_self_hosted:
    runs-on: [self-hosted, android]
    env:
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      APPIUM_URL: http://127.0.0.1:4723/wd/hub
      APP_URL: /home/saraperez/Downloads/app.apk
      AUTOMATION_NAME: UiAutomator2
      PLATFORM_NAME: Android
      PLATFORM_VERSION: "14"
      DEVICE_NAME: test
      AVD_NAME: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: npm install appium@next
      - run: nohup npx appium --base-path /wd/hub > appium.log 2>&1 &
      - name: Run Tests (local debug)
        run: |
          mvn -B -e -X -Dtest=apptests.CucumberRunnerTest test \
            -DAPP_URL=${{ env.APP_URL }} \
            -DAPPIUM_URL=${{ env.APPIUM_URL }} \
            -DDEVICE_NAME="${{ env.DEVICE_NAME }}" \
            -DPLATFORM_VERSION="${{ env.PLATFORM_VERSION }}" \
            -DAUTOMATION_NAME=${{ env.AUTOMATION_NAME }} \
            -DLOGIN_EMAIL=${{ env.LOGIN_EMAIL }} \
            -DLOGIN_PASSWORD=${{ env.LOGIN_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: local-surefire-reports
          path: target/surefire-reports/**
